export declare const CUSTOM_APPLICATION_SUFFIX = "app";
export declare const CUSTOM_METADATA_SUFFIX = "md";
export declare const EMAIL_SERVICES_FUNCTION_SUFFIX = "xml";
export declare const FIELD_DIRECTORY_NAME = "fields";
export declare const FLOW_XML_NAME = "Flow";
export declare const INFOLDER_SUFFIX = "Folder";
export declare const LABEL_DECOMPOSED_SUFFIX = "label";
export declare const MASTER_DETAIL_TAG = "<type>MasterDetail</type>";
export declare const METAFILE_SUFFIX = "-meta.xml";
export declare const META_REGEX: RegExp;
export declare const OBJECT_TRANSLATION_META_XML_SUFFIX = "objectTranslation-meta.xml";
export declare const OBJECT_TRANSLATION_TYPE = "CustomObjectTranslation";
export declare const OBJECT_TYPE = "CustomObject";
export declare const PERMISSIONSET_OBJECTSETTINGS_FOLDER = "objectSettings";
export declare const PERMISSIONSET_TYPE = "PermissionSet";
export declare const SHARING_RULE_TYPE = "SharingRules";
export declare const SUB_OBJECT_TYPES: string[];
export declare const TERRITORY_MODEL_TYPE = "Territory2Model";
export declare const TRANSLATION_EXTENSION = "translation";
export declare const TRANSLATION_TYPE = "Translations";
export declare const WORKFLOW_TYPE = "Workflow";
