name: Install Salesforce CLI
description: Install Node.js 24 and Salesforce CLI globally

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Salesforce CLI
      shell: bash
      run: |
        echo "Installing new version of Salesforce CLI..."
        npm install @salesforce/cli --global
